name: "Mirror TEI dev branch to I18n-TEI main"
on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Mirror to I18n-TEI
        env: 
          SSH_PRIVATE_KEY: ${{ secrets.TEIBOT_PRIVATE_KEY }}
          ACTION_USER_EMAIL: ${{ secrets.I18N_USER_EMAIL }}
          ACTION_USER_NAME: ${{ secrets.I18N_USER_NAME }}
        uses: ./.github/actions/mirror-to-i18n